companyDB:
  - driver: mysql
    open: root@tcp(127.0.0.1:3306)/company

employeeDB:
  - driver: mysql
    open: root@tcp(127.0.0.1:3306)/employee1
  - driver: mysql
    open: root@tcp(127.0.0.1:3306)/employee2
